// ── check-flags.mjs ───────────────────────────────────────────
// Build-time flag gate. Every nation in data/nations.json must have a
// flag at /flags/<fifa>.svg. Writes data/flags-manifest.json (fifa →
// path) and EXITS 1 if any flag is missing — we fail loudly here rather
// than render a blank in the table (prompt §5).
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const flagsDir = path.join(root, "flags");
const nations = JSON.parse(fs.readFileSync(path.join(root, "data", "nations.json"), "utf8"));

const present = new Set(
  fs.existsSync(flagsDir) ? fs.readdirSync(flagsDir).filter((f) => f.endsWith(".svg")).map((f) => f.replace(/\.svg$/, "")) : []
);

const manifest = {};
const missing = [];
for (const n of nations) {
  if (present.has(n.fifa)) manifest[n.fifa] = `flags/${n.fifa}.svg`;
  else missing.push(`${n.fifa} (${n.name})`);
}

fs.writeFileSync(
  path.join(root, "data", "flags-manifest.json"),
  JSON.stringify({ _comment: "fifa code → flag path. Generated by scripts/check-flags.mjs.", flags: manifest }, null, 2) + "\n"
);

if (missing.length) {
  process.stderr.write(`\n[flags] ✗ ${missing.length}/${nations.length} flags MISSING in /flags/ — refusing to ship blanks:\n  ${missing.join("\n  ")}\n`);
  process.exit(1);
}
process.stdout.write(`[flags] ✓ all ${nations.length} flags present\n`);
